# Cours

* [Documentation officielle - NumPy](https://numpy.org/doc/stable/index.html)
* [Documentation officielle - les types NumPy](https://numpy.org/doc/stable/user/basics.types.html)
* [Documentation officielle - np.random.Generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)
* [Documentation officielle - les constantes](https://numpy.org/doc/stable/reference/constants.html)
* [Youtube - Numpy in 5 minutes](https://www.youtube.com/watch?v=xECXZ3tyONo)
* [OpenClassRooms - Plongez en détail dans la librairie NumPy](https://openclassrooms.com/fr/courses/4452741-decouvrez-les-librairies-python-pour-la-data-science/4740941-plongez-en-detail-dans-la-librairie-numpy)

# Sommaire

* [np.array / zeros / ones / full / empty  / linspace / arange / eye + like version](#npzeros)
* [proprietes + infos utiles](#prorpietes)
* [operateurs + where](#operateurs)
* [np.shape / reshape](#shape)
* [vecteur / matrice / tenseur + indexing & slicing](#vectmatten)
* [np.random](#nprandom)
* [np.concatenate, vstack, split](#concatenate)
* [fonctions logiques](#fonctionslogiques)

# Introduction

NumPy permet de charger, stocker et manipuler efficacement les données. 

Elles peuvent venir de sources très variées, mais nous pouvons toujours les considérer comme des tableaux de nombres. 

Par exemple, une image peut être considérée comme un tableau de deux dimensions (une matrice) où chaque nombre représente l'intensité lumineuse d'un pixel.

<a id="npzeros"></a>

## np.array / zeros / ones / full / empty / linspace / arange / eye + like version

empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [150]:
import numpy as np

a_list = ["a","b","c","1","4","8"]
print("a_list")
print(a_list)
print("np.array(a_list)")
print(np.array(a_list))
print()

b_list = [["a","b","c"],["1","4","8"]]
print("b_list")
print(b_list)
print("np.array(b_list)")
print(np.array(b_list))
print()

print("np.zeros")
print(np.zeros(10, dtype=int))
print(np.zeros((2,2)))
print()

print("np.zeros")
print(np.zeros(10, dtype=int))
print(np.zeros((2,2)))
print()

print("np.ones")
print(np.ones(10))
print()

print("np.full")
print(np.full((3,2),np.arange(2)))
print()

print("np.empty")
print(np.empty((3,2)))
print()

print("np.linspace")
print(np.linspace(5,17,8, dtype=int))
print()

print("np.arange")
print(np.arange(1,9,step=2))
print()


vect = np.array([0,2,4,6,8])
print("vect")
print(vect)
print()

print("np.zeros_like")
print(np.zeros_like(vect))
print()

print("np.ones_like")
print(np.ones_like(vect))
print()

print("np.empty_like")
print(np.empty_like(vect))
print()

print("np.full_like")
print(np.full_like(vect, 9))
print()

# Une liste de listes est transformée en un tableau multi-dimensionnel
print("une liste de liste")
print(np.array([range(i, i + 3) for i in [2, 4, 6]])) 
print()

# matrice identité
print("matrice identité")
print(np.eye(3)) 


a_list
['a', 'b', 'c', '1', '4', '8']
np.array(a_list)
['a' 'b' 'c' '1' '4' '8']

b_list
[['a', 'b', 'c'], ['1', '4', '8']]
np.array(b_list)
[['a' 'b' 'c']
 ['1' '4' '8']]

np.zeros
[0 0 0 0 0 0 0 0 0 0]
[[0. 0.]
 [0. 0.]]

np.zeros
[0 0 0 0 0 0 0 0 0 0]
[[0. 0.]
 [0. 0.]]

np.ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

np.full
[[0 1]
 [0 1]
 [0 1]]

np.empty
[[2.5e-323 3.5e-323]
 [0.0e+000 3.0e-323]
 [2.0e-323 4.9e-324]]

np.linspace
[ 5  6  8 10 11 13 15 17]

np.arange
[1 3 5 7]

vect
[0 2 4 6 8]

np.zeros_like
[0 0 0 0 0]

np.ones_like
[1 1 1 1 1]

np.empty_like
[1 1 1 1 1]

np.full_like
[9 9 9 9 9]

une liste de liste
[[2 3 4]
 [4 5 6]
 [6 7 8]]

matrice identité
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<a id="proprietes"></a>

## proprietes + infos utiles

In [166]:
rng = np.random.default_rng(np.random.PCG64(9964)) # une seed donné au BitGenerators PCG64

vals_int = rng.integers(10, size=6)
print("nombre de dimensions de vals_int: {}".format(vals_int.ndim))
print("forme de vals_int: {}".format(vals_int.shape))
print("taille de vals_int: {}".format(vals_int.size))
print("type de vals_int: {}".format(vals_int.dtype))
print()

vals_int2 = rng.integers(10, size=(8,4))
print("nombre de dimensions de vals_int2: {}".format(vals_int2.ndim))
print("forme de vals_int2: {}".format(vals_int2.shape))
print("taille de vals_int2: {}".format(vals_int2.size))
print("type de vals_int2: {}".format(vals_int2.dtype))
print()


print("vals_int2")
print(vals_int2)
print()
print("np.sum(vals_int2) : {}".format(np.sum(vals_int2)))
print("np.sum(vals_int2,axis=0) : {}".format(np.sum(vals_int2,axis=0))) # somme des colonnes
print("np.sum(vals_int2,axis=1) : {}".format(np.sum(vals_int2,axis=1))) # somme des lignes
print("np.prod(vals_int2): {}".format(np.prod(vals_int2)))
print("np.mean(vals_int2): {}".format(np.mean(vals_int2)))
print("np.std(vals_int2): {}".format(np.std(vals_int2))) #ecart type
print("np.var(vals_int2): {}".format(np.var(vals_int2)))
print("np.min(vals_int2): {}".format(np.min(vals_int2)))
print("np.max(vals_int2): {}".format(np.max(vals_int2)))
print("np.argmin(vals_int2): {}".format(np.argmin(vals_int2)))
print("np.argmax(vals_int2): {}".format(np.argmax(vals_int2)))

nombre de dimensions de vals_int: 1
forme de vals_int: (6,)
taille de vals_int: 6
type de vals_int: int64

nombre de dimensions de vals_int2: 2
forme de vals_int2: (8, 4)
taille de vals_int2: 32
type de vals_int2: int64

vals_int2
[[3 1 0 7]
 [6 9 2 1]
 [4 6 6 2]
 [4 6 8 1]
 [5 5 6 5]
 [9 0 6 5]
 [5 9 1 2]
 [5 1 1 7]]

np.sum(vals_int2) : 138
np.sum(vals_int2,axis=0) : [41 37 30 30]
np.sum(vals_int2,axis=1) : [11 18 18 19 21 20 17 14]
np.prod(vals_int2): 0
np.mean(vals_int2): 4.3125
np.std(vals_int2): 2.7092146002116553
np.var(vals_int2): 7.33984375
np.min(vals_int2): 0
np.max(vals_int2): 9
np.argmin(vals_int2): 2
np.argmax(vals_int2): 5


<a id="operateurs"></a>

## opérateurs + where

In [163]:
import numpy as np

z = np.arange(10,20,1)

print("z: {}".format(z))
print("z+30: {}".format(z+30))
print("z==13: {}".format(z == 13))
print("z<13: {}".format(z < 13))
print("z>13: {}".format(z > 13))
print("z[z>3]: {}".format(z[z > 3]))
print("np.where(z > 13): " , np.where(z > 13))
print("np.where(z > 13, 99,-1): ", np.where(z > 13, 99,-1)) # on remplace par 99 les index du tableau renvoyé par z>3 et les autres par -1
print()

x = np.arange(1,11,1)
y = np.arange(10,20,1)

print("x: {}".format(x))
print("y: {}".format(y))
print("x+y: {}".format(x+y))
print("x*y: {}".format(x*y))
print("x/y: {}".format(x/y))
print("x//y: {}".format(x//y)) #division avec arrondi
print("y%x: {}".format(y%x))
print("x@y: {}".format(x@y)) # dot product




z: [10 11 12 13 14 15 16 17 18 19]
z+30: [40 41 42 43 44 45 46 47 48 49]
z==13: [False False False  True False False False False False False]
z<13: [ True  True  True False False False False False False False]
z>13: [False False False False  True  True  True  True  True  True]
z[z>3]: [10 11 12 13 14 15 16 17 18 19]
np.where(z > 13):  (array([4, 5, 6, 7, 8, 9], dtype=int64),)
np.where(z > 13, 99,-1):  [-1 -1 -1 -1 99 99 99 99 99 99]

x: [ 1  2  3  4  5  6  7  8  9 10]
y: [10 11 12 13 14 15 16 17 18 19]
x+y: [11 13 15 17 19 21 23 25 27 29]
x*y: [ 10  22  36  52  70  90 112 136 162 190]
x/y: [0.1        0.18181818 0.25       0.30769231 0.35714286 0.4
 0.4375     0.47058824 0.5        0.52631579]
x//y: [0 0 0 0 0 0 0 0 0 0]
y%x: [0 1 0 1 4 3 2 1 0 9]
x@y: 880


<a id="shape"></a>

## np.shape / reshape

In [153]:
import numpy as np

tab = np.zeros(10, dtype=int)
print("tab")
print(tab)
print()

print("tab.shape")
print(tab.shape)
print()

print("np.shape(tab)")
print(np.shape(tab))
print()

print("tab.reshape(5,2)")
print(tab.reshape(5,2)) #la taille de reshape doit être égale à la taille de l'élément à reshape
print()

print("np.reshape(tab, (5,2))")
print(np.reshape(tab, (5,2)))
print()

tab
[0 0 0 0 0 0 0 0 0 0]

tab.shape
(10,)

np.shape(tab)
(10,)

tab.reshape(5,2)
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

np.reshape(tab, (5,2))
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]



<a id="vectmatten"></a>

## vecteur / matrice / tenseur + indexing & slicing

* slicing :
  * x\[début:fin:pas\]
  * Le début peut être omis si on veut commencer au début de la liste (c'est à dire si début = 0)
  * La fin peut être omise si on veut aller jusqu'au bout de la liste (c'est à dire fin = -1 ou fin = len(liste))
  * Le pas, ainsi que le dernier  :, peuvent être omis si le pas est de 1 (-1 si la fin est inférieure au début). 

In [14]:
import numpy as np

rng = np.random.default_rng()

vecteur = rng.integers(10, size=4) # renvoie une liste de 4 valeurs aléatoires
matrice = rng.integers(10, size=(4,3)) # renvoie une liste de 4 listes de 2 valeurs aléatoires comprises entre 0 & 1
tenseur = rng.integers(10, size=(4,3,2)) # renvoie une liste de 4 listes de 3 listes de 2 valeurs aléatoires comprises entre 0 & 1

# énorme tenseur mais qui ne contient que 2 éléments max à chaque fois
# la dernière valeur de la size égale le nombre max d'éléments
# test = rng.integers(10, size=(8,7,6,5,4,3,2)) 

print("---------------")
print("--- vecteur ---")
print("---------------")
print("vecteur :",vecteur)
print("vecteur[0] :", vecteur[0])
print("vecteur[:2] :", vecteur[:2]) # deux premiers éléments (pas de 1 par défaut) (équivalent à [0:2:1] ou [:2:])
print("vecteur[2:] :", vecteur[2:]) # du troisième au dernier élément (équivalent à [2:len(vecteur):1])
print("vecteur[::2] :", vecteur[::2]) # 1 élément sur deux en commençant à 0 et allant jusqu'à la fin
print("vecteur[::-1] :", vecteur[::-1]) # inverse le vecteur
print("vecteur[-1] : ",vecteur[-1])
print()
print("---------------")
print("--- matrice ---")
print("---------------")
print("matrice")
print(matrice)
print()
print("matrice[::-1]")
print(matrice[::-1])
print()

print("matrice[1,1]", matrice[1,1])
print()
print("matrice[1,:]", matrice[1,:]) #ligne 1
print()
print("matrice[:,1]")
print(matrice[:,1].reshape(matrice.shape[0],1)) # colonne 1
print()

# somme les lignes entre elles élément par élément
for i in range(0, len(matrice)):
    print("ligne {} : {}".format(i+1, matrice[i,:]))
print("somme   : {}".format(np.sum(matrice,0))) 
print()

# somme des colonnes entre elles élément par élément
for i in range(0, len(matrice[0])):
    print("colonne {} : {}".format(i+1, matrice[:,i]))
print("somme     : {}".format(np.sum(matrice,1))) 
print()

print("---------------")
print("--- tenseur ---")
print("---------------")
print(tenseur)


---------------
--- vecteur ---
---------------
vecteur : [0 7 3 1]
vecteur[0] : 0
vecteur[:2] : [0 7]
vecteur[2:] : [3 1]
vecteur[::2] : [0 3]
vecteur[::-1] : [1 3 7 0]
vecteur[-1] :  1

---------------
--- matrice ---
---------------
matrice
[[7 8 0]
 [3 4 3]
 [1 3 9]
 [7 6 4]]

matrice[::-1]
[[7 6 4]
 [1 3 9]
 [3 4 3]
 [7 8 0]]

matrice[1,1] 4

matrice[1,:] [3 4 3]

matrice[:,1]
[[8]
 [4]
 [3]
 [6]]

ligne 1 : [7 8 0]
ligne 2 : [3 4 3]
ligne 3 : [1 3 9]
ligne 4 : [7 6 4]
somme   : [18 21 16]

colonne 1 : [7 3 1 7]
colonne 2 : [8 4 3 6]
colonne 3 : [0 3 9 4]
somme     : [15 10 13 17]

---------------
--- tenseur ---
---------------
[[[2 1]
  [5 8]
  [1 8]]

 [[7 8]
  [3 6]
  [7 9]]

 [[3 0]
  [7 8]
  [9 4]]

 [[7 6]
  [5 8]
  [5 2]]]


<a id="nprandom"></a>

## np.random

Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.

Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

Generator can be used as a replacement for RandomState. 

* random.random_sample / rand --> Generator.random
* random.random_integers / randint --> Generator.integers
* random.choice --> Generator.choice

By default, Generator uses bits provided by PCG64 which has better statistical properties than the legacy MT19937 used in RandomState.

[Documentation Random](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)

In [155]:
import numpy as np

rng = np.random.default_rng() # nouvelle instance de Generators
rng2 = np.random.default_rng(np.random.PCG64(1564)) # une seed donné au BitGenerators PCG64

vals = rng.standard_normal(10)
vals_int = rng2.integers(10, size=10)
vals_choice = rng2.choice([0,2,6], size=10)

print(vals)
print(vals_int)
print(vals_choice)


[ 0.00873984 -1.42717197  0.49926206 -0.22015211  0.8562113   1.33748957
 -0.52390622  0.31847349 -0.55737797  0.24477643]
[1 2 8 1 7 3 5 6 4 7]
[0 6 2 2 6 0 0 2 2 0]


<a id="concatenate"></a>

## np.concatenate, vstack, split

In [156]:
import numpy as np

x = np.arange(10)
y = np.arange(100,110)
rng = np.random.default_rng()
z = rng.integers(10,size=(6,10))

print("x: ",x)
print("y: ",y)
print()

print("np.concatenate([x,y]") 
print(np.concatenate([x,y]))
print()

print("np.split(x,2)")
print(np.split(x,2)) # coupe en deux

print("np.split(x,[2,5])")
print(np.split(x,[2,5])) #arr[:2] + arr[2:5] + arr[5:]
print()

print("z: ") 
print(z)
print()

print("np.split(z,2)")
print(np.split(z,2)) # coupe en deux selon l'axe des lignes #vsplit
print()

print("np.split(z,2, axis=1)")
print(np.split(z,2, axis=1)) # coupe en deux selon l'axe des colonnes #hsplit
print()

print("np.vstack([x,z])")
print(np.vstack([x,z]))
print()

print("np.vstack([z,y])")
print(np.vstack([z,y]))
print()




x:  [0 1 2 3 4 5 6 7 8 9]
y:  [100 101 102 103 104 105 106 107 108 109]

np.concatenate([x,y]
[  0   1   2   3   4   5   6   7   8   9 100 101 102 103 104 105 106 107
 108 109]

np.split(x,2)
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
np.split(x,[2,5])
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

z: 
[[7 6 5 1 4 2 3 1 2 7]
 [3 6 4 2 4 9 4 6 4 1]
 [3 8 0 9 1 9 3 6 5 1]
 [4 9 0 7 1 5 4 7 2 1]
 [4 6 0 5 9 0 7 3 8 3]
 [9 9 9 9 5 6 4 0 4 9]]

np.split(z,2)
[array([[7, 6, 5, 1, 4, 2, 3, 1, 2, 7],
       [3, 6, 4, 2, 4, 9, 4, 6, 4, 1],
       [3, 8, 0, 9, 1, 9, 3, 6, 5, 1]], dtype=int64), array([[4, 9, 0, 7, 1, 5, 4, 7, 2, 1],
       [4, 6, 0, 5, 9, 0, 7, 3, 8, 3],
       [9, 9, 9, 9, 5, 6, 4, 0, 4, 9]], dtype=int64)]

np.split(z,2, axis=1)
[array([[7, 6, 5, 1, 4],
       [3, 6, 4, 2, 4],
       [3, 8, 0, 9, 1],
       [4, 9, 0, 7, 1],
       [4, 6, 0, 5, 9],
       [9, 9, 9, 9, 5]], dtype=int64), array([[2, 3, 1, 2, 7],
       [9, 4, 6, 4, 1],
       [9, 3, 6, 5, 1],
    

<a id="fonctionslogiques"></a>

 ## fonctions logiques

In [171]:
import numpy as np

rng = np.random.default_rng()
x1 = rng.choice([True,False], size=10)
x2 = rng.choice([True,False], size=10)

print("x1: ", x1)
print("x2: ", x2)

print()
print("np.any(x1)", np.any(x1))
print("np.all(x1)", np.all(x1))
print("logical_not(x1)",np.logical_not(x1))

print()
print("logical_and(x1, x2)",np.logical_and(x1, x2))
print("logical_or(x1, x2)",np.logical_or(x1, x2))
print("logical_xor(x1, x2)",np.logical_xor(x1, x2))

print()
print("np.array_equal(x1,x2)",np.array_equal(x1,x2))
print("array_equiv(x1,x2)",np.array_equiv(x1,x2))



x1:  [ True  True  True  True False False False False  True False]
x2:  [False False False False False  True  True False  True False]

np.any(x1) True
np.all(x1) False
logical_not(x1) [False False False False  True  True  True  True False  True]

logical_and(x1, x2) [False False False False False False False False  True False]
logical_or(x1, x2) [ True  True  True  True False  True  True False  True False]
logical_xor(x1, x2) [ True  True  True  True False  True  True False False False]

np.array_equal(x1,x2) False
array_equiv(x1,x2) False
