# Cours

# Sommaire

In [1]:
import numpy as np

vecteur = np.random.rand(4) # renvoie une liste de 4 valeurs aléatoires comprises entre 0 & 1
matrice = np.random.rand(4,3) # renvoie une liste de 4 listes de 2 valeurs aléatoires comprises entre 0 & 1
tenseur = np.random.rand(4,3,2) # renvoie une liste de 4 listes de 3 listes de 2 valeurs aléatoires comprises entre 0 & 1

print("---------------")
print("--- vecteur ---")
print("---------------")
print(vecteur)
print()
print("---------------")
print("--- matrice ---")
print("---------------")
print(matrice)
print()
print("---------------")
print("--- tenseur ---")
print("---------------")
print(tenseur)

---------------
--- vecteur ---
---------------
[0.97970079 0.31002598 0.03049281 0.09600296]

---------------
--- matrice ---
---------------
[[0.29621346 0.9503757  0.8560037 ]
 [0.78148955 0.53061894 0.92834684]
 [0.60969986 0.61566686 0.08962422]
 [0.88717601 0.16081395 0.48589182]]

---------------
--- tenseur ---
---------------
[[[0.5254432  0.48697899]
  [0.42561893 0.12221236]
  [0.36877247 0.87832685]]

 [[0.67983902 0.5586112 ]
  [0.04999478 0.06300505]
  [0.23554925 0.33049438]]

 [[0.10974588 0.8735356 ]
  [0.00294334 0.1586423 ]
  [0.22846318 0.72651978]]

 [[0.11633657 0.98892834]
  [0.61427168 0.14752817]
  [0.75466042 0.39340171]]]


In [2]:
# les matrices
# 3 listes de 2 éléments
# shape (3,) <=> (3,1)
print("--------------------")
print("--- les matrices ---")
print("--------------------")
matrice = np.random.rand(3,2)
print(type(matrice))
print(matrice)
print()

for i in range(0, len(matrice)):
    print("ligne {} : {} : {} : {}".format(i+1, matrice[i,:], type(matrice[i,:]), matrice[i,:].shape))
print("somme   : {}".format(np.sum(matrice,0))) # somme les lignes entre elles
print()

for i in range(0, len(matrice[0])):
    print("colonne {} : {} : {} : {}".format(i+1, matrice[:,i], type(matrice[:,i]), matrice[:,i].shape))
print("somme     : {}".format(np.sum(matrice,1))) # somme des colonnes

print()

--------------------
--- les matrices ---
--------------------
<class 'numpy.ndarray'>
[[0.35987112 0.88955992]
 [0.31679006 0.21934216]
 [0.09480088 0.63882475]]

ligne 1 : [0.35987112 0.88955992] : <class 'numpy.ndarray'> : (2,)
ligne 2 : [0.31679006 0.21934216] : <class 'numpy.ndarray'> : (2,)
ligne 3 : [0.09480088 0.63882475] : <class 'numpy.ndarray'> : (2,)
somme   : [0.77146207 1.74772683]

colonne 1 : [0.35987112 0.31679006 0.09480088] : <class 'numpy.ndarray'> : (3,)
colonne 2 : [0.88955992 0.21934216 0.63882475] : <class 'numpy.ndarray'> : (3,)
somme     : [1.24943103 0.53613222 0.73362564]

